source 'http://rubygems.org'

# gem 'sinatra', '1.3.2'
# gem 'json', '1.7.3'

group :test do
  gem 'cucumber', '1.3.15'
  gem 'rspec', '2.99.0'
  gem 'httparty', '0.13.1'
  gem 'childprocess', '0.5.3'
end
