// Automatically generated by MockGen. DO NOT EDIT!
// Source: ../etcd/etcd_factory.go

package mock_supervisor

import (
	gomock "github.com/innotech/hydra/vendors/code.google.com/p/gomock/gomock"
	config "github.com/innotech/hydra/vendors/github.com/coreos/etcd/config"

	. "github.com/innotech/hydra/etcd"
)

// Mock of EtcdBuilder interface
type MockEtcdBuilder struct {
	ctrl     *gomock.Controller
	recorder *_MockEtcdBuilderRecorder
}

// Recorder for MockEtcdBuilder (not exported)
type _MockEtcdBuilderRecorder struct {
	mock *MockEtcdBuilder
}

func NewMockEtcdBuilder(ctrl *gomock.Controller) *MockEtcdBuilder {
	mock := &MockEtcdBuilder{ctrl: ctrl}
	mock.recorder = &_MockEtcdBuilderRecorder{mock}
	return mock
}

func (_m *MockEtcdBuilder) EXPECT() *_MockEtcdBuilderRecorder {
	return _m.recorder
}

func (_m *MockEtcdBuilder) Build() EtcdService {
	ret := _m.ctrl.Call(_m, "Build")
	ret0, _ := ret[0].(EtcdService)
	return ret0
}

func (_mr *_MockEtcdBuilderRecorder) Build() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Build")
}

func (_m *MockEtcdBuilder) Config(config *config.Config) {
	_m.ctrl.Call(_m, "Config", config)
}

func (_mr *_MockEtcdBuilderRecorder) Config(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Config", arg0)
}
