// Automatically generated by MockGen. DO NOT EDIT!
// Source: cluster_inspector.go

package mock_supervisor

import (
	gomock "github.com/innotech/hydra/vendors/code.google.com/p/gomock/gomock"
)

// Mock of ClusterAnalyzer interface
type MockClusterAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *_MockClusterAnalyzerRecorder
}

// Recorder for MockClusterAnalyzer (not exported)
type _MockClusterAnalyzerRecorder struct {
	mock *MockClusterAnalyzer
}

func NewMockClusterAnalyzer(ctrl *gomock.Controller) *MockClusterAnalyzer {
	mock := &MockClusterAnalyzer{ctrl: ctrl}
	mock.recorder = &_MockClusterAnalyzerRecorder{mock}
	return mock
}

func (_m *MockClusterAnalyzer) EXPECT() *_MockClusterAnalyzerRecorder {
	return _m.recorder
}

func (_m *MockClusterAnalyzer) Run(ch chan string) {
	_m.ctrl.Call(_m, "Run", ch)
}

func (_mr *_MockClusterAnalyzerRecorder) Run(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run", arg0)
}
