// Automatically generated by MockGen. DO NOT EDIT!
// Source: peers_monitor.go

package mock_supervisor

import (
	gomock "github.com/innotech/hydra/vendors/code.google.com/p/gomock/gomock"

	. "github.com/innotech/hydra/supervisor"
)

// Mock of FolderMonitor interface
type MockFolderMonitor struct {
	ctrl     *gomock.Controller
	recorder *_MockFolderMonitorRecorder
}

// Recorder for MockFolderMonitor (not exported)
type _MockFolderMonitorRecorder struct {
	mock *MockFolderMonitor
}

func NewMockFolderMonitor(ctrl *gomock.Controller) *MockFolderMonitor {
	mock := &MockFolderMonitor{ctrl: ctrl}
	mock.recorder = &_MockFolderMonitorRecorder{mock}
	return mock
}

func (_m *MockFolderMonitor) EXPECT() *_MockFolderMonitorRecorder {
	return _m.recorder
}

func (_m *MockFolderMonitor) Run(ch chan []Peer) {
	_m.ctrl.Call(_m, "Run", ch)
}

func (_mr *_MockFolderMonitorRecorder) Run(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run", arg0)
}
