// Automatically generated by MockGen. DO NOT EDIT!
// Source: etcd_manager.go

package mock_supervisor

import (
	gomock "github.com/innotech/hydra/vendors/code.google.com/p/gomock/gomock"
)

// Mock of EtcdController interface
type MockEtcdController struct {
	ctrl     *gomock.Controller
	recorder *_MockEtcdControllerRecorder
}

// Recorder for MockEtcdController (not exported)
type _MockEtcdControllerRecorder struct {
	mock *MockEtcdController
}

func NewMockEtcdController(ctrl *gomock.Controller) *MockEtcdController {
	mock := &MockEtcdController{ctrl: ctrl}
	mock.recorder = &_MockEtcdControllerRecorder{mock}
	return mock
}

func (_m *MockEtcdController) EXPECT() *_MockEtcdControllerRecorder {
	return _m.recorder
}

func (_m *MockEtcdController) Restart() {
	_m.ctrl.Call(_m, "Restart")
}

func (_mr *_MockEtcdControllerRecorder) Restart() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Restart")
}

func (_m *MockEtcdController) Start() {
	_m.ctrl.Call(_m, "Start")
}

func (_mr *_MockEtcdControllerRecorder) Start() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Start")
}

func (_m *MockEtcdController) Stop() {
	_m.ctrl.Call(_m, "Stop")
}

func (_mr *_MockEtcdControllerRecorder) Stop() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Stop")
}
